language: android
android:
  components:
    - build-tools-21.1.2    # The BuildTools version used by project
    - android-22            # The SDK version used to compile your project

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19


before_install:
  - chmod +x gradlew


# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

#script: ./gradlew connectedAndroidTest